[package]
name = "pulse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
cpal = "0.16"
crossbeam-channel = "0.5"
crossterm = "0.29"
ratatui = { version = "0.29", features = ["all-widgets", "crossterm"] }
realfft = "3.5.0"
